# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='业务线名')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='业务名')),
                ('cpu_count', models.IntegerField(null=True, verbose_name='CPU个数')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server', to='falcon.Business', verbose_name='机房')),
            ],
        ),
    ]
